{% set name = "pycares" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 025b6c2ffea4e9fb8f9a097381c2fecb24aff23fbd6906e70da22ec9ba60e19d

build:
  number: 0
  skip: True  # [py<39]
  script_env:
    - PYCARES_USE_SYSTEM_LIB=1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi >=1.5.0
    - setuptools
    - wheel
    - c-ares 1.17
  run:
    - python
    - cffi >=1.5.0
    - idna >=2.1
    - c-ares # bounds through run_exports

test:
  source_files:
    - tests
  imports:
    - pycares
  commands:
    - python -m pycares google.com
    - pip check
    # getting pycares.errno.ARES_ETIMEOUT instead of pycares.errno.ARES_ECONNREFUSED on some tests.
    - pytest -v -k "not (test_channel_local_ip or test_channel_local_ip2 or test_custom_resolvconf or test_query_a_rotate)"
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/pycares/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface for c-ares'
  description: |
    pycares is a Python module which provides an interface to c-ares. c-ares
    is a C library that performs DNS requests and name resolutions
    asynchronously.
  doc_url: https://pycares.readthedocs.io/
  dev_url: https://github.com/saghul/pycares

extra:
  recipe-maintainers:
    - CurtLH
